/**
 * File:        LogManager.java
 * Author:      MarasmiumDev (info@marasmium.dev)
 * Created:     2026.04.22
 * Purpose:     Defines the main class of the application framework's logging system
 */

package dev.marasmium.kit.applib.logging;

import dev.marasmium.kit.applib.App;

import java.io.FileWriter;
import java.io.IOException;
import java.time.DateTimeException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.locks.ReentrantLock;

/**
 * The main class of the application framework's logging system
 */
public class LogManager {

    /**
     * The datetime format for timestamps at the beginning of log messages
     */
    private String timestampFormat = null;
    /**
     * Whether the logging system will write messages to the console
     */
    private boolean consoleOutputEnabled = false;
    /**
     * Whether the logging system will write messages to its current output file
     */
    private boolean outputFileEnabled = false;
    /**
     * The path of the logging system's current output file
     */
    private String outputFilePath = null;
    /**
     * Java file handle for the logging system's current output file
     */
    private FileWriter outputFileWriter = null;
    /**
     * Scope lock for thread-safety while writing logs
     */
    private final ReentrantLock logLock = new ReentrantLock();

    /**
     * Initialize the MarasmiumKit application framework's logging system
     * @param timestampFormat The initial format to apply to timestamps generated by the logging system
     * @param consoleOutputEnabled Whether the logging system will initially write messages to the console
     * @param outputFileEnabled Whether the logging system will initially write messages to a file
     * @param outputFilePath The initial file path for the logging system to write messages to
     * @return Whether the parameters were valid and the logging system was initialized successfully
     */
    public boolean initialize(String timestampFormat, boolean consoleOutputEnabled, boolean outputFileEnabled,
                              String outputFilePath) {
        // Initialize memory
        if (!setTimestampFormat(timestampFormat)) {
            return false;
        }
        setConsoleOutputEnabled(consoleOutputEnabled);
        setOutputFileEnabled(outputFileEnabled);
        if (!setOutputFilePath(outputFilePath)) {
            return false;
        }
        App.Log.write(LogSource.Log, LogLevel.Info, "Initialized logging system");
        return true;
    }

    /**
     * Write a log message
     * @param source The source flag for this message
     * @param level The level/severity flag for this message
     * @param data The message data to write
     */
    public void write(LogSource source, LogLevel level, Object... data) {
        if (source == null || level == null || data == null) {
            return;
        }
        logLock.lock();
        // Compile message data
        StringBuilder message = new StringBuilder(getTimestamp() + ": [" + source + "] [" + level + "] ");
        for (Object o : data) {
            if (o != null) {
                message.append(o);
            } else {
                message.append("[null]");
            }
        }
        message.append("\n");
        // Print to the console and/or output file
        if (consoleOutputEnabled) {
            System.out.print(message);
        }
        if (outputFileEnabled) {
            if (outputFileWriter != null) {
                try {
                    outputFileWriter.write(message.toString());
                    outputFileWriter.flush();
                } catch (IOException _) {
                    outputFileEnabled = false;
                    outputFilePath = null;
                    outputFileWriter = null;
                    write(LogSource.Log, LogLevel.Warning, "Log file inaccessible, disabled file output");
                }
            }
        }
        try {
            logLock.unlock();
        } catch (IllegalMonitorStateException _) {
            System.out.println("Failed to unlock logging system scope lock");
        }
    }

    /**
     * Write a log message with the default level/severity flag
     * @param source The source flag for this message
     * @param data The message data to write
     */
    public void write(LogSource source, Object... data) {
        write(source, new LogLevel(), data);
    }

    /**
     * Write a log message with the default source flag
     * @param level The level/severity flag for this message
     * @param data The message data to write
     */
    public void write(LogLevel level, Object... data) {
        write(new LogSource(), level, data);
    }

    /**
     * Write a log message with the default source and level/severity flag
     * @param data The message data to write
     */
    public void write(Object... data) {
        write(new LogSource(), new LogLevel(), data);
    }

    /**
     * Free/de-initialize the memory of the application framework's logging system
     * @return Whether the logging system was destroyed successfully and cleanly
     */
    public boolean destroy() {
        App.Log.write(LogSource.Log, LogLevel.Info, "Destroying logging system");
        boolean success = true;
        // Reset memory
        timestampFormat = "";
        consoleOutputEnabled = false;
        outputFileEnabled = false;
        outputFilePath = "";
        if (outputFileWriter != null) {
            // Close the still-open output file
            try {
                outputFileWriter.flush();
                outputFileWriter.close();
            } catch (IOException _) {
                success = false;
            }
            outputFileWriter = null;
        }
        return success;
    }

    /**
     * Get a current timestamp in the logging system's timestamp format
     * @return The current date and time as a string
     */
    private String getTimestamp() {
        if (timestampFormat == null) {
            return "";
        }
        DateTimeFormatter formatter;
        // Use the current timestamp format if valid
        try {
            formatter = DateTimeFormatter.ofPattern(timestampFormat);
        } catch (IllegalArgumentException _) {
            formatter = DateTimeFormatter.ISO_LOCAL_DATE_TIME;
        }
        // Test if the format can be used on this system
        String timestamp;
        try {
            timestamp = formatter.format(LocalDateTime.now());
        } catch (DateTimeException _) {
            return "";
        }
        return timestamp;
    }

    /**
     * Get the current format for timestamps attached to log messages
     * @return The current timestamp format
     */
    public String getTimestampFormat() {
        if (timestampFormat == null) {
            return "";
        }
        return timestampFormat;
    }

    /**
     * Set the format for timestamps attached to log messages
     * @param timestampFormat The new timestamp format
     * @return Whether the new timestamp format was valid and could be used
     */
    public boolean setTimestampFormat(String timestampFormat) {
        if (timestampFormat == null) {
            return false;
        }
        // Test whether the new format is valid
        try {
            DateTimeFormatter.ofPattern(timestampFormat);
        } catch (IllegalArgumentException _) {
            return false;
        }
        // Test whether the new format can be used on this system
        String current = this.timestampFormat;
        this.timestampFormat = timestampFormat;
        if (getTimestamp().isEmpty()) {
            this.timestampFormat = current;
            return false;
        }
        return true;
    }

    /**
     * Test whether the logging system currently writes message to the console
     * @return Whether console output is currently enabled
     */
    public boolean isConsoleOutputEnabled() {
        return consoleOutputEnabled;
    }

    /**
     * Set whether the logging system will write messages to the console
     * @param consoleOutputEnabled Whether console output will be enabled
     */
    public void setConsoleOutputEnabled(boolean consoleOutputEnabled) {
        this.consoleOutputEnabled = consoleOutputEnabled;
    }

    /**
     * Test whether the logging system currently writes messages to its output file
     * @return Whether writing messages to the output file is enabled
     */
    public boolean isOutputFileEnabled() {
        return outputFileEnabled;
    }

    /**
     * Set whether the logging system will write messages to its output file
     * @param outputFileEnabled Whether writing messages to the output file will be enabled
     */
    public void setOutputFileEnabled(boolean outputFileEnabled) {
        this.outputFileEnabled = outputFileEnabled;
    }

    /**
     * Get the current path of the logging system's output file
     * @return The output file path
     */
    public String getOutputFilePath() {
        if (outputFilePath == null) {
            return "";
        }
        return outputFilePath;
    }

    /**
     * Set the path of the logging system's output file and close the previous file
     * @param outputFilePath The new output file path or empty string to indicate no output file
     * @return Whether the old file (if present) could be closed and the new file (if present) could be opened
     */
    public boolean setOutputFilePath(String outputFilePath) {
        if (outputFilePath == null) {
            return false;
        }
        this.outputFilePath = outputFilePath;
        boolean success = true;
        // Close the old output file
        if (outputFileWriter != null) {
            try {
                outputFileWriter.flush();
                outputFileWriter.close();
            } catch (IOException _) {
                success = false;
            }
            outputFileWriter = null;
        }
        // Open a new output file if one was given
        if (outputFilePath.isEmpty()) {
            return success;
        }
        try {
            outputFileWriter = new FileWriter(outputFilePath);
        } catch (IOException _) {
            success = false;
        }
        return success;
    }

}
